name = "hl-nmrk-subscription-handling"
type = "javascript"
compatibility_date = "2026-01-08"

[build]
command = ""  # no build needed, handled by echo "skip"

[site]
bucket = "."        # optional, can leave
entry-point = "."   # optional, can leave
