name = "hl-nmrk-subscription-handling"
type = "javascript"
compatibility_date = "2026-01-08"

# No build needed, Worker is plain JS
[build]
command = ""  

[env.production]
# Optional, can leave empty for now
