name = "hl-nmrk-subscription-handling"
type = "javascript"
compatibility_date = "2026-01-08"

main = "worker.js"  # THIS IS THE ENTRY POINT

[build]
command = ""  # no build

# You can leave [site] out because Worker is fetching from GitHub
